version: "2"
services:
  php:
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html/
    links:
      - db
    networks:
      - default
  db:
    image: mysql:5.7.10
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "123456789"
      MYSQL_DATABASE: desafio-credere
    volumes:
      - desafio-credere:/var/lib/mysql
      - ./config:/backup/
    networks:
      - default
volumes:
  desafio-credere: